#!/usr/bin/env python

from settings import change_settings

class PasswordGenerator:
 def __init__(self, settings=None):
  if settings is None:
   settings = {'length': 8, 'UPPER' : True, 'lower' : True, 'numb6r' : True, 'speci@l' : True}
  self.settings = settings

 def generate_password(self):
  # Add code to generate a password based on the settings
  print("Generating password...")

 def show_settings(self):
  print("Settings: " + str(self.settings))
 
 def change_settings(self):
    change_settings(self.settings)

print('\nWelcome to Password Generator!')

pg = PasswordGenerator()

while True:
    user = input('''\nWhat to do?
    List of commands:
    1 - generate password 
    2 - view generation settings
    3 - change settings
    ''')

    if user == '1':
        pg.generate_password()
    elif user == '2':
        pg.show_settings()
    elif user == '3':
        pg.change_settings()
    else:
        print("Invalid command, try again")