#!/usr/bin/env python

from generate_password import PasswordGenerator

pg = PasswordGenerator()

while True:
    user = input('''\nWhat to do?
    List of commands:
    1 - generate password 
    2 - view generation settings
    3 - change settings
    0 - exit
    ''')

    if user == '1':
        pg.generate_password()
    elif user == '2':
        pg.show_settings()
    elif user == '3':
        pg.change_settings()
    elif user == '0':
        break
    else:
        print("Invalid command, try again")